name: CI

on:
  push:
    branches: [ master, dev, ci_testing, bb_next ]
  pull_request:
    branches: [ master ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        llvm_version: [16]

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: bootstrap + compile
        run: |
          . env.sh
          make all

      - name: run unit-tests
        run: |
          . env.sh
          make test
